name: Validate Content

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - run: uv sync
      - run: uv run ./validator.py
